_BASE_: [
  '../datasets/xd_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_270e.yml',
  '_base_/yolov3_r50vd_dcn.yml',
  '_base_/yolov3_reader.yml',
]

snapshot_epoch: 1
weights: output/yolov3_r50vd_dcn_270e_xd/model_final
